language: node_js
node_js: lts/*
env:
  - HUGO_VER=0.42.2
cache: yarn
install: 
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.tar.gz
  - tar xfvz hugo_${HUGO_VER}_Linux-64bit.tar.gz
before_script:
  - yarn global add gulp-cli
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  repo: omahasymphonicchorus.github.io
  target-branch: master
  on:
    branch: master